Repository konflux-ci/release-service-catalog, pull requests merged in 2024-09, with the labels that each got.

#535 fix(RELEASE-1059): fix linting issues in collect-cosign-params task
  tasks/cleanup-workspace/tests/test-cleanup-workspace-internalrequests.yaml
  tasks/collect-cosign-params/README.md
  tasks/collect-cosign-params/collect-cosign-params.yaml
  tasks/collect-cosign-params/tests/test-collect-cosign-params-no-secret-in-data.yaml
  tasks/collect-cosign-params/tests/test-collect-cosign-params.yaml
Labels: lgtm

#544 fix(RELEASE-1064): fix linting issues in create-advisory task
  tasks/create-advisory/README.md
  tasks/create-advisory/create-advisory.yaml
  tasks/create-advisory/tests/mocks.sh
  tasks/create-advisory/tests/test-create-advisory-fail-both-prod-and-pending.yaml
  tasks/create-advisory/tests/test-create-advisory-fail-no-prod-or-pending.yaml
  tasks/create-advisory/tests/test-create-advisory-fail-no-rpa.yaml
  tasks/create-advisory/tests/test-create-advisory-fail-no-snapshot.yaml
Labels: lgtm

#547 feat(RELEASE-1116): timestamp variable is for build date
  tasks/apply-mapping/README.md
  tasks/apply-mapping/apply-mapping.yaml
  tasks/apply-mapping/tests/mocks.sh
  tasks/apply-mapping/tests/test-apply-mapping-fail-tag-expansion.yaml
  tasks/apply-mapping/tests/test-apply-mapping-tag-expansion.yaml
Labels: lgtm

#546 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: lgtm

#539 fix(KFLUXBUGS-1498): expose the fbc opt in flag
  tasks/add-fbc-contribution/README.md
  tasks/add-fbc-contribution/add-fbc-contribution.yaml
  tasks/add-fbc-contribution/tests/mocks.sh
  tasks/add-fbc-contribution/tests/test-add-fbc-contribution.yaml
Labels: lgtm

#551 feat: nicer display for fbc pipelines
  pipelines/fbc-release/README.md
  pipelines/fbc-release/fbc-release.yaml
Labels: lgtm

#510 feat(MMENG-4169): add publish-to-mrrc task
  tasks/publish-to-mrrc/README.md
  tasks/publish-to-mrrc/publish-to-mrrc.yaml
  tasks/publish-to-mrrc/tests/mocks.sh
  tasks/publish-to-mrrc/tests/pre-apply-task-hook.sh
  tasks/publish-to-mrrc/tests/test-publish-to-mrrc-failure-no-mrrc-file.yaml
  tasks/publish-to-mrrc/tests/test-publish-to-mrrc.yaml
Labels: ok-to-test

#558 feat(RELEASE-1144): push content sets to Pyxis
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-external-registry/README.md
  pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/rhtap-service-push/README.md
  pipelines/rhtap-service-push/rhtap-service-push.yaml
  tasks/push-rpm-data-to-pyxis/README.md
  tasks/push-rpm-data-to-pyxis/push-rpm-data-to-pyxis.yaml
  tasks/push-rpm-data-to-pyxis/tests/mocks.sh
  tasks/push-rpm-data-to-pyxis/tests/pre-apply-task-hook.sh
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-failure.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-multi-arch.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-no-pyxis-file.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-parallel.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-single-arch.yaml
Labels: lgtm

#531 feat(RELEASE-909): add collect-collectors-data task
  tasks/collect-collectors-resources/README.md
  tasks/collect-collectors-resources/collect-collectors-resources.yaml
  tasks/collect-collectors-resources/tests/pre-apply-task-hook.sh
  tasks/collect-collectors-resources/tests/test-collect-collectors-data-fail-missing-cr.yaml
  tasks/collect-collectors-resources/tests/test-collect-collectors-data.yaml
Labels: lgtm

#560 fix: skip empty target indexes
  tasks/update-ocp-tag/README.md
  tasks/update-ocp-tag/tests/test-update-ocp-tag-staged-index.yaml
  tasks/update-ocp-tag/update-ocp-tag.yaml
Labels: lgtm

#561 fix: apply-mapping no longer fails if build-date is null
  tasks/apply-mapping/README.md
  tasks/apply-mapping/apply-mapping.yaml
Labels: lgtm

#548 feat(ISV-5125): Add unique tag info to purl
  tasks/populate-release-notes-images/README.md
  tasks/populate-release-notes-images/populate-release-notes-images.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-multiple-images.yaml
Labels: lgtm, ok-to-test

#564 Revert "fix(KFLUXBUGS-752): skip signing if already signed"
  tasks/rh-sign-image/README.md
  tasks/rh-sign-image/rh-sign-image.yaml
  tasks/rh-sign-image/tests/mocks.sh
  tasks/rh-sign-image/tests/test-rh-sign-image-skip-signing-when-signed.yaml
Labels: lgtm

#568 fix(RELEASE-1178): fetching of Dockerfile oci artifact
  tasks/create-pyxis-image/README.md
  tasks/create-pyxis-image/create-pyxis-image.yaml
  tasks/create-pyxis-image/tests/mocks.sh
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-rhpush-and-commontag.yaml
Labels: lgtm

#571 fix(KFLUXBUGS-1647): searching for wrong json field on get-ocp-version
  tasks/get-ocp-version/get-ocp-version.yaml
  tasks/get-ocp-version/tests/mocks.sh
Labels: lgtm

#563 feat(CLDX-81): add sign-binaries task to push-binaries pipeline
  pipelines/push-binaries-to-dev-portal/README.md
  pipelines/push-binaries-to-dev-portal/push-binaries-to-dev-portal.yaml
  tasks/sign-binaries/README.md
  tasks/sign-binaries/sign-binaries.yaml
  tasks/sign-binaries/tests/pre-apply-task-hook.sh
  tasks/sign-binaries/tests/test-sign-binaries.yaml
Labels: ok-to-test

#572 feat(RELEASE-1161): add reduce-snapshot task
  pipelines/push-binaries-to-dev-portal/README.md
  pipelines/push-binaries-to-dev-portal/push-binaries-to-dev-portal.yaml
  pipelines/push-disk-images-to-cdn/README.md
  pipelines/push-disk-images-to-cdn/push-disk-images-to-cdn.yaml
  pipelines/push-to-external-registry/README.md
  pipelines/push-to-external-registry/push-to-external-registry.yaml
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-external-registry/README.md
  pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/rhtap-service-push/README.md
  pipelines/rhtap-service-push/rhtap-service-push.yaml
Labels: lgtm

#577 chore(RELEASE-1184): increase concurrency and timeout for signing
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  tasks/rh-sign-image/README.md
  tasks/rh-sign-image/rh-sign-image.yaml
Labels: lgtm

#578 fix(RELEASE-1187): error when Dockerfile has a different filename
  tasks/create-pyxis-image/README.md
  tasks/create-pyxis-image/create-pyxis-image.yaml
  tasks/create-pyxis-image/tests/mocks.sh
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
Labels: lgtm

#580 chore(RELEASE-903): remove lingering RSC reference
  tasks/create-advisory/tests/test-create-advisory-fail-wrong-type.yaml
Labels: lgtm

#556 feat(ISV-5129): create product-level SBOMs
  tasks/create-product-sbom/README.md
  tasks/create-product-sbom/create-product-sbom.yaml
  tasks/create-product-sbom/tests/test-create-product-sbom-basic.yaml
  tasks/create-product-sbom/tests/test-create-product-sbom-multiple-purls.yaml
  tasks/populate-release-notes-images/README.md
  tasks/populate-release-notes-images/populate-release-notes-images.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-single-image.yaml
Labels: lgtm, ok-to-test
