Repository konflux-ci/release-service-catalog, pull requests merged in 2024-07, with the labels that each got.

#427 refactor(RELEASE-920): drop images support in push-snapshot
  tasks/push-snapshot/README.md
  tasks/push-snapshot/push-snapshot.yaml
  tasks/push-snapshot/tests/mocks.sh
  tasks/push-snapshot/tests/test-push-snapshot-addgitshatag.yaml
  tasks/push-snapshot/tests/test-push-snapshot-addsourceshatag.yaml
  tasks/push-snapshot/tests/test-push-snapshot-addtimestamptag.yaml
  tasks/push-snapshot/tests/test-push-snapshot-both.yaml
  tasks/push-snapshot/tests/test-push-snapshot-defaulttag.yaml
  tasks/push-snapshot/tests/test-push-snapshot-digests-match.yaml
  tasks/push-snapshot/tests/test-push-snapshot-fail-addsourceshatag.yaml
  tasks/push-snapshot/tests/test-push-snapshot-fail-no-data-file.yaml
  tasks/push-snapshot/tests/test-push-snapshot-fail-tagless-component.yaml
  tasks/push-snapshot/tests/test-push-snapshot-pushsourcecontainer-component.yaml
  tasks/push-snapshot/tests/test-push-snapshot-pushsourcecontainer-defaults.yaml
  tasks/push-snapshot/tests/test-push-snapshot-pushsourcecontainer-skip-existing.yaml
  tasks/push-snapshot/tests/test-push-snapshot-pushsourcecontainer.yaml
  tasks/push-snapshot/tests/test-push-snapshot-retries.yaml
  tasks/push-snapshot/tests/test-push-snapshot.yaml
Labels: lgtm

#432 feat(CLOUDDST-22189): add publish-to-cgw task
  tasks/publish-to-cgw/README.md
  tasks/publish-to-cgw/publish-to-cgw.yaml
  tasks/publish-to-cgw/tests/mocks.sh
  tasks/publish-to-cgw/tests/pre-apply-task-hook.sh
  tasks/publish-to-cgw/tests/test-publish-to-cgw.yaml
Labels: lgtm, ok-to-test

#464 feat(RELEASE-981): refactor verify-access-to-resources into a standalone task
  pipelines/fbc-release/README.md
  pipelines/fbc-release/fbc-release.yaml
  pipelines/push-binaries-to-dev-portal/README.md
  pipelines/push-binaries-to-dev-portal/push-binaries-to-dev-portal.yaml
  pipelines/push-to-external-registry/README.md
  pipelines/push-to-external-registry/push-to-external-registry.yaml
  pipelines/release-to-github/README.md
  pipelines/release-to-github/release-to-github.yaml
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-external-registry/README.md
  pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/rhtap-service-push/README.md
  pipelines/rhtap-service-push/rhtap-service-push.yaml
  tasks/verify-access-to-resources/README.md
  tasks/verify-access-to-resources/tests/pre-apply-task-hook.sh
  tasks/verify-access-to-resources/tests/test-verify-access-to-resources-permissions.yaml
  tasks/verify-access-to-resources/verify-access-to-resources.yaml
Labels: lgtm

#470 fix(RELEASE-1005): set -x in rh-sign-image task
  tasks/rh-sign-image/README.md
  tasks/rh-sign-image/rh-sign-image.yaml
Labels: lgtm

#467 feat(CLOUDDST-22843): add rh-sign-image-cosign task
  tasks/rh-sign-image-cosign/README.md
  tasks/rh-sign-image-cosign/rh-sign-image-cosign.yaml
  tasks/rh-sign-image-cosign/tests/mocks.sh
  tasks/rh-sign-image-cosign/tests/pre-apply-task-hook.sh
  tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-multiple-components.yaml
  tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-single-component.yaml
Labels: needs-ok-to-test

#465 chore: rework task ordering
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
Labels: lgtm

#474 fix(RELEASE-1004): fix various multi-arch issues
  tasks/push-snapshot/push-snapshot.yaml
Labels: lgtm

#468 feat(CLOUDDST-22844): add cosign tasks to pipelines
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  tasks/collect-cosign-params/README.md
  tasks/collect-cosign-params/collect-cosign-params.yaml
  tasks/collect-cosign-params/tests/test-collect-cosign-params-no-secret-in-data.yaml
  tasks/collect-cosign-params/tests/test-collect-cosign-params.yaml
Labels: lgtm, ok-to-test

#478 fix(RELEASE-951): remove SARIF upload & integrate printout for Checkton
  .github/workflows/lint.yaml
Labels: lgtm

#475 fix(CLDX-128): update tasks as per testing of push-to-dev-portal pipeline
  pipelines/push-binaries-to-dev-portal/README.md
  pipelines/push-binaries-to-dev-portal/push-binaries-to-dev-portal.yaml
  tasks/prepare-exodus-params/README.md
  tasks/prepare-exodus-params/prepare-exodus-params.yaml
  tasks/publish-to-cgw/README.md
  tasks/publish-to-cgw/publish-to-cgw.yaml
  tasks/publish-to-cgw/tests/mocks.sh
  tasks/push-to-cdn/README.md
  tasks/push-to-cdn/push-to-cdn.yaml
Labels: ok-to-test

#480 fix: incorrect task references in push-binaries-to-dev-portal pipeline
  pipelines/push-binaries-to-dev-portal/README.md
  pipelines/push-binaries-to-dev-portal/push-binaries-to-dev-portal.yaml
Labels: lgtm

#483 feat(RELEASE-1030): add cdn system to check-data-keys
  tasks/check-data-keys/README.md
  tasks/check-data-keys/check-data-keys.yaml
  tasks/check-data-keys/tests/test-check-data-keys-fail-missing-cdn-key.yaml
  tasks/check-data-keys/tests/test-check-data-keys.yaml
Labels: lgtm

#487 fix(RELEASE-1025): bump image in publish-to-cgw
  tasks/publish-to-cgw/README.md
  tasks/publish-to-cgw/publish-to-cgw.yaml
  tasks/publish-to-cgw/tests/test-publish-to-cgw.yaml
Labels: lgtm

#490 fix(CLOUDDST-23731): cosign after push
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  tasks/collect-cosign-params/collect-cosign-params.yaml
  tasks/rh-sign-image-cosign/rh-sign-image-cosign.yaml
  tasks/rh-sign-image-cosign/tests/pre-apply-task-hook.sh
Labels: ok-to-test

#471 feat(RELEASE-971): add task to push disk images
  tasks/push-disk-images/README.md
  tasks/push-disk-images/push-disk-images.yaml
  tasks/push-disk-images/tests/mocks.sh
  tasks/push-disk-images/tests/pre-apply-task-hook.sh
  tasks/push-disk-images/tests/test-push-disk-images-fail-ir-failure.yaml
  tasks/push-disk-images/tests/test-push-disk-images-fail-no-data.yaml
  tasks/push-disk-images/tests/test-push-disk-images-fail-no-snapshot.yaml
  tasks/push-disk-images/tests/test-push-disk-images-production.yaml
  tasks/push-disk-images/tests/test-push-disk-images-qa.yaml
  tasks/push-disk-images/tests/test-push-disk-images-stage.yaml
Labels: lgtm

#484 feat(RELEASE-974): add push-disk-images-to-cdn pipeline
  pipelines/push-disk-images-to-cdn/README.md
  pipelines/push-disk-images-to-cdn/push-disk-images-to-cdn.yaml
Labels: lgtm

#497 fix: override timeout of push-disk-images task
  pipelines/push-disk-images-to-cdn/README.md
  pipelines/push-disk-images-to-cdn/push-disk-images-to-cdn.yaml
Labels: lgtm

#498 fix: check-data-keys shows failure output on cdn system
  tasks/check-data-keys/README.md
  tasks/check-data-keys/check-data-keys.yaml
Labels: lgtm

#499 test(RELEASE-1019): fix kubectl mock in tasks
  tasks/create-advisory/tests/mocks.sh
  tasks/embargo-check/tests/mocks.sh
Labels: lgtm
