Repository konflux-ci/release-service-catalog, pull requests merged in 2024-08, with the labels that each got.

#494 fix: block advisory pipeline progress on the ec check
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
Labels: lgtm

#501 feat(RELEASE-1044): add requireInternalServices parameter to verify-a…
  pipelines/fbc-release/README.md
  pipelines/fbc-release/fbc-release.yaml
  pipelines/push-binaries-to-dev-portal/README.md
  pipelines/push-binaries-to-dev-portal/push-binaries-to-dev-portal.yaml
  pipelines/push-disk-images-to-cdn/README.md
  pipelines/push-disk-images-to-cdn/push-disk-images-to-cdn.yaml
  pipelines/push-to-external-registry/README.md
  pipelines/push-to-external-registry/push-to-external-registry.yaml
  pipelines/release-to-github/README.md
  pipelines/release-to-github/release-to-github.yaml
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-external-registry/README.md
  pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/rhtap-service-push/README.md
  pipelines/rhtap-service-push/rhtap-service-push.yaml
  tasks/verify-access-to-resources/README.md
  tasks/verify-access-to-resources/tests/test-verify-access-to-resources-permissions.yaml
  tasks/verify-access-to-resources/verify-access-to-resources.yaml
Labels: lgtm

#495 fix(RELEASE-1029): support partial oci auth match
  tasks/push-snapshot/README.md
  tasks/push-snapshot/push-snapshot.yaml
Labels: lgtm

#508 fix(KONFLUX-3991): sign manifest list digests
  tasks/rh-sign-image/README.md
  tasks/rh-sign-image/rh-sign-image.yaml
  tasks/rh-sign-image/tests/test-rh-sign-image-single-component-multi-arch.yaml
Labels: lgtm

#509 chore(RELEASE-394): standardized changelog format
  hub/kubernetes-actions/README.md
  pipelines/e2e/README.md
  pipelines/fbc-release/README.md
  pipelines/push-binaries-to-dev-portal/README.md
  pipelines/push-disk-images-to-cdn/README.md
  pipelines/push-to-external-registry/README.md
  pipelines/release-to-github/README.md
  pipelines/rh-advisories/README.md
  pipelines/rh-push-to-external-registry/README.md
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rhtap-service-push/README.md
  tasks/add-fbc-contribution/README.md
  tasks/apply-mapping/README.md
  tasks/base64-encode-checksum/README.md
  tasks/check-data-keys/README.md
  tasks/check-fbc-packages/README.md
  tasks/cleanup-workspace/README.md
  tasks/collect-cosign-params/README.md
  tasks/collect-data/README.md
  tasks/collect-gh-params/README.md
  tasks/collect-pyxis-params/README.md
  tasks/collect-slack-notification-params/README.md
  tasks/create-advisory/README.md
  tasks/create-github-release/README.md
  tasks/create-internal-request/README.md
  tasks/create-pyxis-image/README.md
  tasks/embargo-check/README.md
  tasks/extract-binaries-from-image/README.md
  tasks/extract-index-image/README.md
  tasks/get-ocp-version/README.md
  tasks/prepare-exodus-params/README.md
  tasks/prepare-fbc-release/README.md
  tasks/prepare-validation/README.md
  tasks/publish-index-image/README.md
  tasks/publish-pyxis-repository/README.md
  tasks/publish-to-cgw/README.md
  tasks/pull-disk-images/README.md
  tasks/push-disk-images/README.md
  tasks/push-rpm-manifests-to-pyxis/README.md
  tasks/push-snapshot/README.md
  tasks/push-to-cdn/README.md
  tasks/rh-sign-image-cosign/README.md
  tasks/rh-sign-image/README.md
  tasks/run-file-updates/README.md
  tasks/send-slack-notification/README.md
  tasks/sign-base64-blob/README.md
  tasks/sign-index-image/README.md
  tasks/slack-webhook-notification/README.md
  tasks/update-cr-status/README.md
  tasks/update-infra-deployments/README.md
  tasks/update-ocp-tag/README.md
  tasks/validate-single-component/README.md
Labels: lgtm

#500 feat(CLOUDDST-23791): Set signing identity to reference with tag
  tasks/rh-sign-image-cosign/README.md
  tasks/rh-sign-image-cosign/rh-sign-image-cosign.yaml
  tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-multiple-components.yaml
  tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-single-component.yaml
Labels: lgtm, ok-to-test

#505 chore: remove pull-disk-images task
  tasks/pull-disk-images/README.md
  tasks/pull-disk-images/pull-disk-images.yaml
  tasks/pull-disk-images/tests/mocks.sh
  tasks/pull-disk-images/tests/pre-apply-task-hook.sh
  tasks/pull-disk-images/tests/test-pull-disk-images-fail-duplicate-destination.yaml
  tasks/pull-disk-images/tests/test-pull-disk-images-fail-no-snapshot-file.yaml
  tasks/pull-disk-images/tests/test-pull-disk-images-parallel.yaml
  tasks/pull-disk-images/tests/test-pull-disk-images.yaml
Labels: lgtm

#493 feat(MMENG-4168): add mrrc-collect-params task
  tasks/collect-mrrc-params/README.md
  tasks/collect-mrrc-params/collect-mrrc-params.yaml
  tasks/collect-mrrc-params/tests/test-collect-mrrc-params-fail-no-data.yaml
  tasks/collect-mrrc-params/tests/test-collect-mrrc-params.yaml
Labels: lgtm, ok-to-test

#512 fix: add missing annotation and labels for collect-mrrc-params
  tasks/collect-mrrc-params/collect-mrrc-params.yaml
Labels: lgtm, needs-ok-to-test

#514 feat(RELEASE-985): schema validator for data keys validation
  schema/dataKeys.json
Labels: lgtm

#518 feat(RELEASE-1105): update tekton unit test workflow for internal dir
  .github/scripts/test_tekton_tasks.sh
  .github/workflows/tekton_task_tests.yaml
Labels: lgtm

#522 fix: correct env name in usage comment for tests
  .github/scripts/test_tekton_tasks.sh
Labels: lgtm, needs-ok-to-test

#519 feat(RELEASE-1037): add placeholder internal resources
  internal/pipelines/e2e/README.md
  internal/pipelines/e2e/e2e.yaml
  internal/resources/cleanup-workspace.yaml
  internal/resources/e2e.yaml
  internal/tasks/cleanup-workspace/README.md
  internal/tasks/cleanup-workspace/cleanup-workspace.yaml
  internal/tasks/cleanup-workspace/tests/mocks.sh
  internal/tasks/cleanup-workspace/tests/pre-apply-task-hook.sh
  internal/tasks/cleanup-workspace/tests/test-cleanup-workspace-internalrequests.yaml
  internal/tasks/cleanup-workspace/tests/test-cleanup-workspace-invalid-subdirectory.yaml
  internal/tasks/cleanup-workspace/tests/test-cleanup-workspace-no-subdirectory.yaml
  internal/tasks/cleanup-workspace/tests/test-cleanup-workspace.yaml
Labels: lgtm
