Repository konflux-ci/release-service-catalog, pull requests merged in 2024-06, with the labels that each got.

#436 feat(RELEASE-930): tekton task tests always run
  .github/workflows/tekton_task_tests.yaml
Labels: lgtm

#437 fix: commonTags is empty with new tag format
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
Labels: lgtm

#431 feat(RELEASE-935): add update-cr-status task
  .github/resources/crd_rbac.yaml
  tasks/update-cr-status/README.md
  tasks/update-cr-status/tests/pre-apply-task-hook.sh
  tasks/update-cr-status/tests/test-update-cr-status-missing-rbac.yaml
  tasks/update-cr-status/tests/test-update-cr-status-multiple-result-files.yaml
  tasks/update-cr-status/tests/test-update-cr-status-no-overwrite.yaml
  tasks/update-cr-status/tests/test-update-cr-status-no-results.yaml
  tasks/update-cr-status/tests/test-update-cr-status-nonexistent-status-field.yaml
  tasks/update-cr-status/tests/test-update-cr-status-resource-nonexistent.yaml
  tasks/update-cr-status/tests/test-update-cr-status-results-not-json.yaml
  tasks/update-cr-status/tests/test-update-cr-status.yaml
  tasks/update-cr-status/update-cr-status.yaml
Labels: lgtm

#440 feat(RELEASE-878): collect-data creates result dir
  tasks/collect-data/README.md
  tasks/collect-data/collect-data.yaml
  tasks/collect-data/tests/test-collect-data.yaml
Labels: lgtm

#441 feat(RELEASE-953): create-advisory writes a results file
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  tasks/create-advisory/README.md
  tasks/create-advisory/create-advisory.yaml
  tasks/create-advisory/tests/test-create-advisory-fail-both-prod-and-pending.yaml
  tasks/create-advisory/tests/test-create-advisory-fail-no-data.yaml
  tasks/create-advisory/tests/test-create-advisory-fail-no-prod-or-pending.yaml
  tasks/create-advisory/tests/test-create-advisory-fail-no-rpa.yaml
  tasks/create-advisory/tests/test-create-advisory-fail-no-snapshot.yaml
  tasks/create-advisory/tests/test-create-advisory-fail-orphan.yaml
  tasks/create-advisory/tests/test-create-advisory-pending-repo.yaml
  tasks/create-advisory/tests/test-create-advisory-prod-repo.yaml
Labels: lgtm

#444 fix: add set -x in create-advisory script
  tasks/create-advisory/README.md
  tasks/create-advisory/create-advisory.yaml
  tasks/create-advisory/tests/mocks.sh
Labels: lgtm

#447 feat(RELEASE-938): create-github-release writes a results file
  pipelines/release-to-github/README.md
  pipelines/release-to-github/release-to-github.yaml
  tasks/create-github-release/README.md
  tasks/create-github-release/create-github-release.yaml
  tasks/create-github-release/tests/test-create-github-release.yaml
Labels: lgtm

#451 feat(RELEASE-939): fbc tasks write artifacts to file
  pipelines/fbc-release/README.md
  pipelines/fbc-release/fbc-release.yaml
  tasks/add-fbc-contribution/README.md
  tasks/add-fbc-contribution/add-fbc-contribution.yaml
  tasks/add-fbc-contribution/tests/test-add-fbc-contribution-hotfix.yaml
  tasks/add-fbc-contribution/tests/test-add-fbc-contribution-pre-ga-and-hotfix-failure.yaml
  tasks/add-fbc-contribution/tests/test-add-fbc-contribution-pre-ga.yaml
  tasks/add-fbc-contribution/tests/test-add-fbc-contribution-staged-index.yaml
  tasks/add-fbc-contribution/tests/test-add-fbc-contribution-timeout.yaml
  tasks/add-fbc-contribution/tests/test-add-fbc-contribution.yaml
  tasks/extract-index-image/README.md
  tasks/extract-index-image/extract-index-image.yaml
  tasks/extract-index-image/tests/test-extract-index-image-fail-no-inputdatafile.yaml
  tasks/extract-index-image/tests/test-extract-index-image.yaml
Labels: lgtm

#443 Support multiple components
  tasks/extract-binaries-from-image/README.md
  tasks/extract-binaries-from-image/extract-binaries-from-image.yaml
  tasks/extract-binaries-from-image/tests/mocks.sh
  tasks/extract-binaries-from-image/tests/test-extract-binaries-multiple-components-desired-only.yaml
  tasks/extract-binaries-from-image/tests/test-extract-binaries-multiple-components.yaml
Labels: ok-to-test

#450 feat(RELEASE-940): add update-cr-status to pipelines
  pipelines/fbc-release/README.md
  pipelines/fbc-release/fbc-release.yaml
  pipelines/release-to-github/README.md
  pipelines/release-to-github/release-to-github.yaml
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-external-registry/README.md
  pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/rhtap-service-push/README.md
  pipelines/rhtap-service-push/rhtap-service-push.yaml
Labels: lgtm

#456 chore: bump utils image
  tasks/create-pyxis-image/README.md
  tasks/create-pyxis-image/create-pyxis-image.yaml
  tasks/populate-release-notes-images/README.md
  tasks/populate-release-notes-images/populate-release-notes-images.yaml
  tasks/push-snapshot/README.md
  tasks/push-snapshot/push-snapshot.yaml
Labels: lgtm

#453 feat(RELEASE-937): push-snapshot writes a results file
  pipelines/push-to-external-registry/README.md
  pipelines/push-to-external-registry/push-to-external-registry.yaml
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-external-registry/README.md
  pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/rhtap-service-push/README.md
  pipelines/rhtap-service-push/rhtap-service-push.yaml
  tasks/push-snapshot/README.md
  tasks/push-snapshot/push-snapshot.yaml
  tasks/push-snapshot/tests/test-push-snapshot-addgitshatag.yaml
  tasks/push-snapshot/tests/test-push-snapshot-addsourceshatag.yaml
  tasks/push-snapshot/tests/test-push-snapshot-addtimestamptag.yaml
  tasks/push-snapshot/tests/test-push-snapshot-both.yaml
  tasks/push-snapshot/tests/test-push-snapshot-defaulttag.yaml
  tasks/push-snapshot/tests/test-push-snapshot-digests-match.yaml
  tasks/push-snapshot/tests/test-push-snapshot-fail-addgitshatag.yaml
  tasks/push-snapshot/tests/test-push-snapshot-fail-addsourceshatag.yaml
  tasks/push-snapshot/tests/test-push-snapshot-fail-no-data-file.yaml
  tasks/push-snapshot/tests/test-push-snapshot-fail-no-snapshot-file.yaml
  tasks/push-snapshot/tests/test-push-snapshot-floatingtags.yaml
  tasks/push-snapshot/tests/test-push-snapshot-pushsourcecontainer-skip-existing.yaml
  tasks/push-snapshot/tests/test-push-snapshot-pushsourcecontainer.yaml
  tasks/push-snapshot/tests/test-push-snapshot-retries.yaml
  tasks/push-snapshot/tests/test-push-snapshot-tags.yaml
  tasks/push-snapshot/tests/test-push-snapshot.yaml
Labels: lgtm

#455 feat(CLOUDDST-22189): add prepare-exodus-params task
  tasks/prepare-exodus-params/README.md
  tasks/prepare-exodus-params/prepare-exodus-params.yaml
  tasks/prepare-exodus-params/tests/test-prepare-exodus-params-cdn-live.yaml
  tasks/prepare-exodus-params/tests/test-prepare-exodus-params-cdn-qa.yaml
  tasks/prepare-exodus-params/tests/test-prepare-exodus-params-cdn-stage.yaml
Labels: lgtm, ok-to-test

#435 feat(CLOUDDST-22191): add pipeline for pushing binaries to dev portal
  pipelines/push-binaries-to-dev-portal/README.md
  pipelines/push-binaries-to-dev-portal/push-binaries-to-dev-portal.yaml
Labels: ok-to-test

#433 feat(CLOUDDST-22189): add push-to-cdn task
  tasks/push-to-cdn/README.md
  tasks/push-to-cdn/push-to-cdn.yaml
  tasks/push-to-cdn/tests/mocks.sh
  tasks/push-to-cdn/tests/pre-apply-task-hook.sh
  tasks/push-to-cdn/tests/test-push-to-cdn.yaml
Labels: lgtm, ok-to-test

#424 refactor(RELEASE-920): clean up commonTags parameter
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-external-registry/README.md
  pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/rhtap-service-push/README.md
  pipelines/rhtap-service-push/rhtap-service-push.yaml
  tasks/create-pyxis-image/README.md
  tasks/create-pyxis-image/create-pyxis-image.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-fail-invalid-server.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-fail-no-data-file.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-fail-no-snapshot-file.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-rhpush-and-commontag.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-tag-in-component.yaml
  tasks/populate-release-notes-images/README.md
  tasks/populate-release-notes-images/populate-release-notes-images.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-cves-added.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-fail-missing-data.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-fail-missing-snapshot.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-multiple-images.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-no-overwrite.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-single-image-comp-tags.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-single-image.yaml
Labels: lgtm

#460 fix(RELEASE-979): embargo-check runs before pushing
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
Labels: lgtm
