Repository konflux-ci/release-service-catalog, pull requests merged in 2024-11, with the labels that each got.

#658 Fix the missing pyxis error on rh-push-to-registry-redhat-io
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
Labels: lgtm, ok-to-test

#646 chore(RELEASE-1038): add embargoed-cves internal task and pipeline
  internal/pipelines/check-embargoed-cves/README.md
  internal/pipelines/check-embargoed-cves/check-embargoed-cves.yaml
  internal/resources/check-embargoed-cves-task.yaml
  internal/resources/check-embargoed-cves.yaml
  internal/tasks/check-embargoed-cves-task/README.md
  internal/tasks/check-embargoed-cves-task/check-embargoed-cves-task.yaml
  internal/tasks/check-embargoed-cves-task/tests/mocks.sh
  internal/tasks/check-embargoed-cves-task/tests/pre-apply-task-hook.sh
  internal/tasks/check-embargoed-cves-task/tests/test-check-embargoed-cves-task-embargoed-cve.yaml
  internal/tasks/check-embargoed-cves-task/tests/test-check-embargoed-cves-task-no-access-cve.yaml
  internal/tasks/check-embargoed-cves-task/tests/test-check-embargoed-cves-task-no-embargo.yaml
Labels: lgtm

#661 chore: cleanup examples in internal dir
  internal/pipelines/e2e/README.md
  internal/pipelines/e2e/e2e.yaml
  internal/resources/cleanup-workspace.yaml
  internal/resources/e2e.yaml
  internal/tasks/cleanup-workspace/README.md
  internal/tasks/cleanup-workspace/cleanup-workspace.yaml
  internal/tasks/cleanup-workspace/tests/mocks.sh
  internal/tasks/cleanup-workspace/tests/pre-apply-task-hook.sh
  internal/tasks/cleanup-workspace/tests/test-cleanup-workspace-internalrequests.yaml
  internal/tasks/cleanup-workspace/tests/test-cleanup-workspace-invalid-subdirectory.yaml
  internal/tasks/cleanup-workspace/tests/test-cleanup-workspace-no-subdirectory.yaml
  internal/tasks/cleanup-workspace/tests/test-cleanup-workspace.yaml
Labels: lgtm

#662 fix(KONFLUX-4292): update the step image used in this task
  tasks/push-rpm-data-to-pyxis/README.md
  tasks/push-rpm-data-to-pyxis/push-rpm-data-to-pyxis.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-failure.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-multi-arch.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-parallel.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-single-arch.yaml
Labels: lgtm

#636 feat(RELEASE-1239): print pipeline ref info
  tasks/collect-data/README.md
  tasks/collect-data/collect-data.yaml
  tasks/collect-data/tests/mocks.sh
  tasks/collect-data/tests/pre-apply-task-hook.sh
  tasks/collect-data/tests/test-collect-data-print-pipeline-ref-nongit.yaml
  tasks/collect-data/tests/test-collect-data-print-pipeline-ref.yaml
Labels: lgtm

#668 fix: update `releaseNotes.product_version` regex pattern
  schema/dataKeys.json
Labels: lgtm

#669 fix(KONFLUX-4892): supply sha256 prefix for uncompressed layers
  tasks/create-pyxis-image/README.md
  tasks/create-pyxis-image/create-pyxis-image.yaml
Labels: lgtm

#670 chore: bump release-service-utils image in rh-sign-image-cosigin
  tasks/rh-sign-image-cosign/README.md
  tasks/rh-sign-image-cosign/rh-sign-image-cosign.yaml
  tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-multiple-components.yaml
  tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-single-component.yaml
Labels: lgtm

#674 fix: extend timeout for verify-enterprise-contract task
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
Labels: lgtm

#675 fix(KFLUXBUGS-1848): bump release-service-utils
  tasks/create-pyxis-image/create-pyxis-image.yaml
Labels: lgtm

#677 fix(KFLUXBUGS-1848): associate existing images with a new repo
  tasks/create-pyxis-image/README.md
  tasks/create-pyxis-image/create-pyxis-image.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-dockerfile-not-found.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-fail-dockerfile-not-pulled.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-oci-artifact.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-rhpush-and-commontag.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-with-gzipped-layers.yaml
Labels: lgtm

#679 fix(KFLUXBUGS-1848): fix image id parsing
  tasks/create-pyxis-image/README.md
  tasks/create-pyxis-image/create-pyxis-image.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-dockerfile-not-found.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-fail-dockerfile-not-pulled.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-oci-artifact.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-rhpush-and-commontag.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-with-gzipped-layers.yaml
Labels: lgtm

#678 fix: let apply-mapping retry a few times
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
Labels: lgtm

#691 fix: cves should be permitted
  schema/dataKeys.json
Labels: lgtm

#692 fix: improve cve generation
  tasks/check-data-keys/tests/test-check-data-keys.yaml
  tasks/populate-release-notes-images/populate-release-notes-images.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-cves-added.yaml
Labels: lgtm

#695 fix: allow additional params in the schema
  schema/dataKeys.json
Labels: lgtm

#680 feat(CLDX-189): support pushing to mirror.openshift.com
  schema/dataKeys.json
  tasks/publish-to-cgw/README.md
  tasks/publish-to-cgw/publish-to-cgw.yaml
  tasks/publish-to-cgw/tests/test-publish-to-cgw.yaml
Labels: ok-to-test

#683 fix(CLOUDDST-24922): retry cosign in signing task
  tasks/rh-sign-image-cosign/README.md
  tasks/rh-sign-image-cosign/rh-sign-image-cosign.yaml
  tasks/rh-sign-image-cosign/tests/mocks.sh
  tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-retries.yaml
Labels: ok-to-test

#656 feat(ISV-5128): add new Tekton task to update component sboms
  tasks/push-rpm-data-to-pyxis/README.md
  tasks/push-rpm-data-to-pyxis/push-rpm-data-to-pyxis.yaml
  tasks/push-rpm-data-to-pyxis/tests/mocks.sh
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-cyclonedx.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-failure.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-multi-arch.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-parallel.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-single-arch.yaml
  tasks/update-component-sbom/README.md
  tasks/update-component-sbom/tests/mocks.sh
  tasks/update-component-sbom/tests/pre-apply-task-hook.sh
  tasks/update-component-sbom/tests/test-update-component-sbom-basic.yaml
  tasks/update-component-sbom/update-component-sbom.yaml
Labels: lgtm, ok-to-test

#703 fix(RELEASE-1304): typo when setting default value with jq
  tasks/run-file-updates/README.md
  tasks/run-file-updates/run-file-updates.yaml
Labels: lgtm

#709 fix(RELEASE-993): resolve substitution and incrementer logic issues
  tasks/apply-mapping/README.md
  tasks/apply-mapping/apply-mapping.yaml
Labels: lgtm
