Repository konflux-ci/release-service-catalog, pull requests merged in 2024-12, with the labels that each got.

#713 chore: bump image in create-pyxis-image
  tasks/create-pyxis-image/README.md
  tasks/create-pyxis-image/create-pyxis-image.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-dockerfile-not-found.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-fail-dockerfile-not-pulled.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-oci-artifact.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-rhpush-and-commontag.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-with-gzipped-layers.yaml
Labels: lgtm

#717 feat(RELEASE-1310): add update-cr-status to push-disk-images
  pipelines/push-disk-images-to-cdn/README.md
  pipelines/push-disk-images-to-cdn/push-disk-images-to-cdn.yaml
  tasks/push-disk-images/README.md
  tasks/push-disk-images/push-disk-images.yaml
  tasks/push-disk-images/tests/test-push-disk-images-fail-ir-failure.yaml
  tasks/push-disk-images/tests/test-push-disk-images-fail-no-contentgateway-data.yaml
  tasks/push-disk-images/tests/test-push-disk-images-fail-no-data.yaml
  tasks/push-disk-images/tests/test-push-disk-images-fail-no-snapshot.yaml
  tasks/push-disk-images/tests/test-push-disk-images-production.yaml
  tasks/push-disk-images/tests/test-push-disk-images-qa.yaml
  tasks/push-disk-images/tests/test-push-disk-images-results.yaml
  tasks/push-disk-images/tests/test-push-disk-images-stage.yaml
Labels: lgtm, ok-to-test

#722 docs: update README with actual default value
  tasks/sign-base64-blob/README.md
Labels: lgtm

#721 chore(RELEASE-1191): add simple-signing-pipeline to internal clusters
  internal/resources/collect-simple-signing-params.yaml
  internal/resources/simple-signing-pipeline.yaml
  tasks/collect-simple-signing-params/README.md
Labels: lgtm

#725 fix(RELEASE-1310): add update-cr-status to push-disk-images
  pipelines/push-disk-images-to-cdn/push-disk-images-to-cdn.yaml
Labels: lgtm, needs-ok-to-test

#723 refactor(RELEASE-1191): use simple-signing-pipeline for irs
  pipelines/fbc-release/README.md
  pipelines/fbc-release/fbc-release.yaml
  tasks/rh-sign-image/README.md
  tasks/rh-sign-image/rh-sign-image.yaml
  tasks/rh-sign-image/tests/test-rh-sign-image-ir-failure.yaml
  tasks/rh-sign-image/tests/test-rh-sign-image-multiple-components.yaml
  tasks/rh-sign-image/tests/test-rh-sign-image-push-source-container.yaml
  tasks/rh-sign-image/tests/test-rh-sign-image-single-component-multi-arch.yaml
  tasks/rh-sign-image/tests/test-rh-sign-image-single-component.yaml
  tasks/rh-sign-image/tests/test-rh-sign-image-timeout.yaml
  tasks/sign-index-image/README.md
  tasks/sign-index-image/sign-index-image.yaml
  tasks/sign-index-image/tests/test-sign-index-image-with-pullspec-rewrite.yaml
  tasks/sign-index-image/tests/test-sign-index-image.yaml
Labels: lgtm

#728 docs: Add a pull request template
  CONTRIBUTING.md
  pull_request_template.md
Labels: lgtm, ok-to-test

#733 fix(RELEASE-1339): no longer consult .sign.request
  tasks/sign-base64-blob/README.md
  tasks/sign-base64-blob/sign-base64-blob.yaml
  tasks/sign-base64-blob/tests/test-sign-base64-blob.yaml
Labels: lgtm

#734 feat(RELEASE-1191): diferentiate pyxis and umb in signing part1
  pipelines/simple-signing-pipeline/README.md
  pipelines/simple-signing-pipeline/simple-signing-pipeline.yaml
  tasks/collect-simple-signing-params/README.md
  tasks/collect-simple-signing-params/collect-simple-signing-params.yaml
  tasks/collect-simple-signing-params/tests/pre-apply-task-hook.sh
Labels: lgtm

#726 fix(KFLUXSPRT-794): pass content-gateway token as env var
  tasks/publish-to-cgw/README.md
  tasks/publish-to-cgw/publish-to-cgw.yaml
Labels: ok-to-test

#737 feat(SPSTRAT-466): add pipeline for marketplacesvm
  pipelines/push-disk-images-to-marketplaces/README.md
  pipelines/push-disk-images-to-marketplaces/push-disk-images-to-marketplaces.yaml
Labels: lgtm, needs-ok-to-test

#740 fix(RELEASE-1071): linting issues in extract-index-image
  tasks/extract-index-image/README.md
  tasks/extract-index-image/extract-index-image.yaml
  tasks/extract-index-image/tests/test-extract-index-image-fail-no-inputdatafile.yaml
  tasks/extract-index-image/tests/test-extract-index-image.yaml
Labels: lgtm

#724 feat(ISV-5447): add multi-arch and sha info to release note images
  tasks/populate-release-notes-images/README.md
  tasks/populate-release-notes-images/populate-release-notes-images.yaml
  tasks/populate-release-notes-images/tests/mocks.sh
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-multiple-images.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-single-image.yaml
  tasks/update-component-sbom/README.md
  tasks/update-component-sbom/tests/test-update-component-sbom-basic.yaml
  tasks/update-component-sbom/update-component-sbom.yaml
Labels: ok-to-test

#745 fix(RELEASE-1082): linting issues in push-rpm-manifests-to-pyxis
  tasks/push-rpm-data-to-pyxis/README.md
  tasks/push-rpm-data-to-pyxis/push-rpm-data-to-pyxis.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-cyclonedx.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-failure.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-multi-arch.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-parallel.yaml
  tasks/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-single-arch.yaml
Labels: lgtm

#720 feat(RELEASE-400): adds check-data-keys task in release pipeline
  pipelines/managed/fbc-release/README.md
  pipelines/managed/fbc-release/fbc-release.yaml
  pipelines/managed/push-binaries-to-dev-portal/README.md
  pipelines/managed/push-binaries-to-dev-portal/push-binaries-to-dev-portal.yaml
  pipelines/managed/push-disk-images-to-cdn/README.md
  pipelines/managed/push-disk-images-to-cdn/push-disk-images-to-cdn.yaml
  pipelines/managed/push-to-addons-registry/README.md
  pipelines/managed/push-to-addons-registry/push-to-addons-registry.yaml
  pipelines/managed/push-to-external-registry/README.md
  pipelines/managed/push-to-external-registry/push-to-external-registry.yaml
  pipelines/managed/release-to-github/README.md
  pipelines/managed/release-to-github/release-to-github.yaml
  pipelines/managed/release-to-mrrc/README.md
  pipelines/managed/release-to-mrrc/release-to-mrrc.yaml
  pipelines/managed/rh-advisories/README.md
  pipelines/managed/rh-advisories/rh-advisories.yaml
  pipelines/managed/rh-push-to-external-registry/README.md
  pipelines/managed/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/managed/rh-push-to-registry-redhat-io/README.md
  pipelines/managed/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/managed/rhtap-service-push/README.md
  pipelines/managed/rhtap-service-push/rhtap-service-push.yaml
  schema/dataKeys.json
  tasks/check-data-keys/README.md
  tasks/check-data-keys/check-data-keys.yaml
Labels: lgtm, ok-to-test

#759 fix: strip .git suffix from repo url in check-data-keys
  tasks/check-data-keys/README.md
  tasks/check-data-keys/check-data-keys.yaml
  tasks/check-data-keys/tests/mocks.sh
  tasks/check-data-keys/tests/test-check-data-keys-strip-git-suffix.yaml
Labels: lgtm
