Repository konflux-ci/release-service-catalog, pull requests merged in 2024-10, with the labels that each got.

#582 fix(RELEASE-1093): linting issues in update-infra-deployments task
  tasks/update-infra-deployments/README.md
  tasks/update-infra-deployments/tests/run.yaml
  tasks/update-infra-deployments/tests/test-update-infra-deployments-fail-no-data-file.yaml
  tasks/update-infra-deployments/update-infra-deployments.yaml
Labels: lgtm

#573 feat(ISV-5127): Add new Tekton task to Konflux to upload sbom to Atlas
  tasks/upload-sbom-to-atlas/README.md
  tasks/upload-sbom-to-atlas/tests/mocks.sh
  tasks/upload-sbom-to-atlas/tests/pre-apply-task-hook.sh
  tasks/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-cyclonedx.yaml
  tasks/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-spdx.yaml
  tasks/upload-sbom-to-atlas/upload-sbom-to-atlas.yaml
Labels: ok-to-test

#592 feat(RELEASE-911): add save-collectors-results
  tasks/save-collectors-results/README.md
  tasks/save-collectors-results/save-collectors-results.yaml
  tasks/save-collectors-results/tests/pre-apply-task-hook.sh
  tasks/save-collectors-results/tests/test-save-collectors-results-file-not-json.yaml
  tasks/save-collectors-results/tests/test-save-collectors-results-multiple-result-files.yaml
  tasks/save-collectors-results/tests/test-save-collectors-results-no-results.yaml
  tasks/save-collectors-results/tests/test-save-collectors-results-nonexistent-status-field.yaml
  tasks/save-collectors-results/tests/test-save-collectors-results-not-valid-name.yaml
  tasks/save-collectors-results/tests/test-save-collectors-results-resource-nonexistent.yaml
  tasks/save-collectors-results/tests/test-save-collectors-results.yaml
Labels: lgtm

#575 feat(RELEASE-910): add run-collectors task
  tasks/run-collectors/README.md
  tasks/run-collectors/run-collectors.yaml
  tasks/run-collectors/tests/mocks.sh
  tasks/run-collectors/tests/pre-apply-task-hook.sh
  tasks/run-collectors/tests/test-run-collectors-fail-no-results-dir.yaml
  tasks/run-collectors/tests/test-run-collectors-fail-timeout.yaml
  tasks/run-collectors/tests/test-run-collectors-no-crs.yaml
  tasks/run-collectors/tests/test-run-collectors-parallel.yaml
  tasks/run-collectors/tests/test-run-collectors-rp-only.yaml
  tasks/run-collectors/tests/test-run-collectors-rpa-only.yaml
  tasks/run-collectors/tests/test-run-collectors.yaml
Labels: lgtm

#598 feat(RELEASE-1195): add baseImage key to data mapping
  schema/dataKeys.json
Labels: lgtm

#596 feat(RELEASE-912): add run-collectors pipeline
  pipelines/run-collectors/README.md
  pipelines/run-collectors/run-collectors.yaml
Labels: lgtm

#604 fix: tweak github actions
  .github/workflows/promote_branch.yaml
  .github/workflows/tekton_task_tests.yaml
Labels: lgtm

#610 fix: fail build timestamp expansion for oci artifacts with no labels
  tasks/apply-mapping/apply-mapping.yaml
Labels: lgtm

#607 feat(MMENG-4171): add release-to-mrrc pipeline
  pipelines/release-to-mrrc/README.md
  pipelines/release-to-mrrc/release-to-mrrc.yaml
Labels: lgtm, needs-ok-to-test

#606 fix: avoid duplicates in component tags
  tasks/apply-mapping/README.md
  tasks/apply-mapping/apply-mapping.yaml
  tasks/apply-mapping/tests/test-apply-mapping-tag-expansion.yaml
Labels: lgtm

#616 fix: gitlint installation
  .github/workflows/lint.yaml
Labels: lgtm

#618 chore: allow promotion after 6 days
  .github/scripts/promote_branch.sh
Labels: lgtm

#625 fix: ignore gitlint checks for bots
  .gitlint
Labels: lgtm

#620 feat(CLOUDDST-24467): set rekor in cosign task
  tasks/collect-cosign-params/collect-cosign-params.yaml
  tasks/rh-sign-image-cosign/README.md
  tasks/rh-sign-image-cosign/rh-sign-image-cosign.yaml
  tasks/rh-sign-image-cosign/tests/pre-apply-task-hook.sh
  tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-multiple-components.yaml
  tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-single-component.yaml
Labels: ok-to-test

#633 test: dot in a label for tag expansion
  tasks/apply-mapping/tests/mocks.sh
  tasks/apply-mapping/tests/test-apply-mapping-tag-expansion.yaml
Labels: lgtm

#617 chore: update apply-mapping error message to be more verbose
  tasks/apply-mapping/README.md
  tasks/apply-mapping/apply-mapping.yaml
Labels: lgtm

#614 chore(RELEASE-1143): increase push-disk-images ir timeout to 24h
  tasks/push-disk-images/README.md
  tasks/push-disk-images/push-disk-images.yaml
Labels: lgtm

#628 fix(RELEASE-1068): fix linting issues in create-pyxis-image task
  tasks/create-pyxis-image/README.md
  tasks/create-pyxis-image/create-pyxis-image.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-multi-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-rhpush-and-commontag.yaml
Labels: lgtm

#641 fix: properly expand create-pyxis-image oras args
  tasks/create-pyxis-image/README.md
  tasks/create-pyxis-image/create-pyxis-image.yaml
Labels: lgtm

#642 fix: composing oras args in create-pyxis-image
  tasks/create-pyxis-image/create-pyxis-image.yaml
Labels: lgtm

#631 chore: bump release-service-utils in apply-mapping
  tasks/apply-mapping/apply-mapping.yaml
  tasks/apply-mapping/tests/test-apply-mapping-fail-invalid-label-value.yaml
  tasks/apply-mapping/tests/test-apply-mapping-fail-invalid-tag-variable.yaml
  tasks/apply-mapping/tests/test-apply-mapping-fail-missing-label.yaml
  tasks/apply-mapping/tests/test-apply-mapping-fail-on-empty.yaml
  tasks/apply-mapping/tests/test-apply-mapping-fail-on-invalid-image-reference.yaml
  tasks/apply-mapping/tests/test-apply-mapping-fail-tag-expansion.yaml
  tasks/apply-mapping/tests/test-apply-mapping-multi-redhat-components.yaml
  tasks/apply-mapping/tests/test-apply-mapping-no-data-file.yaml
  tasks/apply-mapping/tests/test-apply-mapping-no-data-mapping.yaml
  tasks/apply-mapping/tests/test-apply-mapping-other-formats.yaml
  tasks/apply-mapping/tests/test-apply-mapping-staged-files-expansion.yaml
  tasks/apply-mapping/tests/test-apply-mapping-tag-expansion.yaml
  tasks/apply-mapping/tests/test-apply-mapping.yaml
Labels: ok-to-test

#648 fix(RELEASE-1268): publish-pyxis-repository after apply-mapping
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
Labels: lgtm

#649 chore(RELEASE-1269): default to RHBA for advisory
  schema/dataKeys.json
  tasks/create-advisory/create-advisory.yaml
  tasks/create-advisory/tests/test-create-advisory-default-type.yaml
Labels: lgtm

#639 chore: skip e2e check for prs from konflux
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Labels: lgtm

#644 test: add create-pyxis-image test for oci artifacts
  tasks/create-pyxis-image/tests/mocks.sh
  tasks/create-pyxis-image/tests/test-create-pyxis-image-oci-artifact.yaml
Labels: lgtm

#650 fix(CLDX-190): changes as per testing sign-binaries task with pipeline
  pipelines/push-binaries-to-dev-portal/README.md
  pipelines/push-binaries-to-dev-portal/push-binaries-to-dev-portal.yaml
  tasks/extract-binaries-from-image/README.md
  tasks/extract-binaries-from-image/extract-binaries-from-image.yaml
  tasks/extract-binaries-from-image/tests/test-extract-binaries-multiple-components-desired-only.yaml
  tasks/prepare-exodus-params/README.md
  tasks/prepare-exodus-params/prepare-exodus-params.yaml
  tasks/prepare-exodus-params/tests/test-prepare-exodus-params-cdn-live.yaml
  tasks/prepare-exodus-params/tests/test-prepare-exodus-params-cdn-qa.yaml
  tasks/prepare-exodus-params/tests/test-prepare-exodus-params-cdn-stage.yaml
  tasks/publish-to-cgw/README.md
  tasks/publish-to-cgw/publish-to-cgw.yaml
Labels: lgtm, ok-to-test
