Repository konflux-ci/release-service-catalog, pull requests merged in 2024-05, with the labels that each got.

#411 refactor(RELEASE-384): rh-sign-image looks at mapping
  tasks/rh-sign-image/README.md
  tasks/rh-sign-image/rh-sign-image.yaml
  tasks/rh-sign-image/tests/mocks.sh
  tasks/rh-sign-image/tests/test-rh-sign-image-push-source-container-in-mapping.yaml
  tasks/rh-sign-image/tests/test-rh-sign-image-single-component-images-key-priority.yaml
Labels: lgtm

#412 refactor(RELEASE-384): publish-pyxis-repository looks at mapping
  tasks/publish-pyxis-repository/README.md
  tasks/publish-pyxis-repository/publish-pyxis-repository.yaml
  tasks/publish-pyxis-repository/tests/test-publish-pyxis-repository-source-container-mapping.yaml
  tasks/publish-pyxis-repository/tests/test-publish-pyxis-repository-source-container-priority.yaml
Labels: lgtm

#403 feat(KFLUXBUGS-1115): add push-rpm-manifests task
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-external-registry/README.md
  pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/rhtap-service-push/README.md
  pipelines/rhtap-service-push/rhtap-service-push.yaml
  tasks/push-rpm-manifests-to-pyxis/README.md
  tasks/push-rpm-manifests-to-pyxis/push-rpm-manifests-to-pyxis.yaml
  tasks/push-rpm-manifests-to-pyxis/tests/mocks.sh
  tasks/push-rpm-manifests-to-pyxis/tests/pre-apply-task-hook.sh
  tasks/push-rpm-manifests-to-pyxis/tests/test-push-rpm-manifests-to-pyxis-failure.yaml
  tasks/push-rpm-manifests-to-pyxis/tests/test-push-rpm-manifests-to-pyxis-no-pyxis-file.yaml
  tasks/push-rpm-manifests-to-pyxis/tests/test-push-rpm-manifests-to-pyxis-parallel.yaml
  tasks/push-rpm-manifests-to-pyxis/tests/test-push-rpm-manifests-to-pyxis.yaml
Labels: do-not-merge

#418 refactor(RELEASE-384): tag expansion done in apply-mapping
  tasks/apply-mapping/README.md
  tasks/apply-mapping/apply-mapping.yaml
  tasks/apply-mapping/tests/mocks.sh
  tasks/apply-mapping/tests/pre-apply-task-hook.sh
  tasks/apply-mapping/tests/test-apply-mapping-tag-expansion.yaml
  tasks/push-snapshot/README.md
  tasks/push-snapshot/push-snapshot.yaml
  tasks/push-snapshot/tests/mocks.sh
  tasks/push-snapshot/tests/test-push-snapshot-tags.yaml
Labels: lgtm

#417 feat(RELEASE-457): improve collect-data logging
  tasks/collect-data/README.md
  tasks/collect-data/collect-data.yaml
Labels: lgtm

#409 verify-enterprise-contract: Support new EXTRA_RULE_DATA parameter
  pipelines/e2e/README.md
  pipelines/e2e/e2e.yaml
  pipelines/fbc-release/README.md
  pipelines/fbc-release/fbc-release.yaml
  pipelines/push-to-external-registry/README.md
  pipelines/push-to-external-registry/push-to-external-registry.yaml
  pipelines/release-to-github/README.md
  pipelines/release-to-github/release-to-github.yaml
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-external-registry/README.md
  pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/rhtap-service-push/README.md
  pipelines/rhtap-service-push/rhtap-service-push.yaml
Labels: lgtm, ok-to-test

#419 refactor(RELEASE-384): commonTags come from snapshot
  tasks/create-pyxis-image/README.md
  tasks/create-pyxis-image/create-pyxis-image.yaml
  tasks/create-pyxis-image/tests/test-create-pyxis-image-tag-in-component.yaml
  tasks/populate-release-notes-images/README.md
  tasks/populate-release-notes-images/populate-release-notes-images.yaml
  tasks/populate-release-notes-images/tests/test-populate-release-notes-images-single-image-comp-tags.yaml
  tasks/rh-sign-image/README.md
  tasks/rh-sign-image/rh-sign-image.yaml
  tasks/rh-sign-image/tests/test-rh-sign-image-single-component-image-tag-in-component.yaml
Labels: lgtm

#423 feat(RELEASE-230): update release service ref to konflux ci org
  .github/scripts/install_crds.sh
  CONTRIBUTING.md
  README.md
Labels: lgtm

#416 fix(RELEASE-916): apply-mapping uses data file, not rpa
  pipelines/push-to-external-registry/README.md
  pipelines/push-to-external-registry/push-to-external-registry.yaml
  pipelines/rh-advisories/README.md
  pipelines/rh-advisories/rh-advisories.yaml
  pipelines/rh-push-to-external-registry/README.md
  pipelines/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/rh-push-to-registry-redhat-io/README.md
  pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/rhtap-service-push/README.md
  pipelines/rhtap-service-push/rhtap-service-push.yaml
  tasks/apply-mapping/README.md
  tasks/apply-mapping/apply-mapping.yaml
  tasks/apply-mapping/tests/test-apply-mapping-fail-on-empty.yaml
  tasks/apply-mapping/tests/test-apply-mapping-no-data-file.yaml
  tasks/apply-mapping/tests/test-apply-mapping-no-data-mapping.yaml
  tasks/apply-mapping/tests/test-apply-mapping-no-rpa.yaml
  tasks/apply-mapping/tests/test-apply-mapping-tag-expansion.yaml
  tasks/apply-mapping/tests/test-apply-mapping.yaml
Labels: lgtm
