Repository konflux-ci/release-service-catalog, pull requests merged in 2025-04, with the labels that each got.

#864 chore(KFLUXVNGD-203): create a release pipeline for tasks bundles
  pipelines/managed/push-tekton-task-bundles-to-external-registry/README.md
  pipelines/managed/push-tekton-task-bundles-to-external-registry/push-tekton-task-bundles-to-external-registry.yaml
Labels: lgtm

#870 fix: improve logging in get-advisory-severity
  tasks/internal/get-advisory-severity/README.md
  tasks/internal/get-advisory-severity/get-advisory-severity.yaml
  tasks/internal/get-advisory-severity/tests/mocks.sh
Labels: lgtm

#874 fix(RELEASE-1512): disable checking of component name in embargo-check
  tasks/managed/embargo-check/README.md
  tasks/managed/embargo-check/embargo-check.yaml
  tasks/managed/embargo-check/tests/test-embargo-check-rh-issue-missing-cve.yaml
  tasks/managed/embargo-check/tests/test-embargo-check-rh-issue-wrong-component.yaml
Labels: lgtm

#868 feat(RELEASE-1394): push disk images use internal task via git resolvers
  internal/resources/push-disk-images.yaml
  pipelines/internal/push-disk-images/README.md
  pipelines/internal/push-disk-images/push-disk-images.yaml
  pipelines/managed/push-disk-images-to-cdn/README.md
  pipelines/managed/push-disk-images-to-cdn/push-disk-images-to-cdn.yaml
  tasks/managed/push-disk-images/README.md
  tasks/managed/push-disk-images/push-disk-images.yaml
  tasks/managed/push-disk-images/tests/test-push-disk-images-fail-ir-failure.yaml
  tasks/managed/push-disk-images/tests/test-push-disk-images-fail-no-contentgateway-data.yaml
  tasks/managed/push-disk-images/tests/test-push-disk-images-fail-no-data.yaml
  tasks/managed/push-disk-images/tests/test-push-disk-images-fail-no-snapshot.yaml
  tasks/managed/push-disk-images/tests/test-push-disk-images-production.yaml
  tasks/managed/push-disk-images/tests/test-push-disk-images-qa.yaml
  tasks/managed/push-disk-images/tests/test-push-disk-images-results.yaml
  tasks/managed/push-disk-images/tests/test-push-disk-images-stage.yaml
Labels: ok-to-test

#873 feat(RELEASE-1514): verify_ec_task_git_revision
  pipelines/managed/e2e/README.md
  pipelines/managed/e2e/e2e.yaml
  pipelines/managed/fbc-release/README.md
  pipelines/managed/fbc-release/fbc-release.yaml
  pipelines/managed/push-artifacts-to-cdn/README.md
  pipelines/managed/push-artifacts-to-cdn/push-artifacts-to-cdn.yaml
  pipelines/managed/push-binaries-to-dev-portal/README.md
  pipelines/managed/push-binaries-to-dev-portal/push-binaries-to-dev-portal.yaml
  pipelines/managed/push-disk-images-to-cdn/README.md
  pipelines/managed/push-disk-images-to-cdn/push-disk-images-to-cdn.yaml
  pipelines/managed/push-disk-images-to-marketplaces/README.md
  pipelines/managed/push-disk-images-to-marketplaces/push-disk-images-to-marketplaces.yaml
  pipelines/managed/push-tekton-task-bundles-to-external-registry/README.md
  pipelines/managed/push-tekton-task-bundles-to-external-registry/push-tekton-task-bundles-to-external-registry.yaml
  pipelines/managed/push-to-addons-registry/README.md
  pipelines/managed/push-to-addons-registry/push-to-addons-registry.yaml
  pipelines/managed/push-to-external-registry/README.md
  pipelines/managed/push-to-external-registry/push-to-external-registry.yaml
  pipelines/managed/release-to-github/README.md
  pipelines/managed/release-to-github/release-to-github.yaml
  pipelines/managed/release-to-mrrc/README.md
  pipelines/managed/release-to-mrrc/release-to-mrrc.yaml
  pipelines/managed/rh-advisories/README.md
  pipelines/managed/rh-advisories/rh-advisories.yaml
  pipelines/managed/rh-push-to-external-registry/README.md
  pipelines/managed/rh-push-to-external-registry/rh-push-to-external-registry.yaml
  pipelines/managed/rh-push-to-registry-redhat-io/README.md
  pipelines/managed/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
  pipelines/managed/rhtap-service-push/README.md
  pipelines/managed/rhtap-service-push/rhtap-service-push.yaml
Labels: lgtm

#889 fix(KONFLUX-7710): formatting of process-file-updates-task result
  tasks/internal/process-file-updates-task/README.md
  tasks/internal/process-file-updates-task/process-file-updates-task.yaml
  tasks/internal/process-file-updates-task/tests/test-process-file-updates-combo.yaml
  tasks/internal/process-file-updates-task/tests/test-process-file-updates-replacements.yaml
  tasks/internal/process-file-updates-task/tests/test-process-file-updates-seed.yaml
Labels: lgtm

#861 fix(RELEASE-1491): add repository param to cleanup_tags
  tasks/managed/create-pyxis-image/README.md
  tasks/managed/create-pyxis-image/create-pyxis-image.yaml
  tasks/managed/create-pyxis-image/tests/mocks.sh
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-dockerfile-not-found.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-fail-dockerfile-not-pulled.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-fail-get-image-architectures.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-multi-arch.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-one-arch.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-oci-artifact.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-multi-arch.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-rhpush-and-commontag.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-skip-layers.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-with-gzipped-layers.yaml
Labels: ok-to-test

#893 chore(RELEASE-1334): remove github workflow pushing to internal
  .github/workflows/copy_development_to_internal.yaml
Labels: lgtm

#857 feat(ISV-5658): retry SBOM push to S3
  pipelines/managed/rh-advisories/README.md
  pipelines/managed/rh-advisories/rh-advisories.yaml
  tasks/managed/collect-atlas-params/README.md
  tasks/managed/collect-atlas-params/collect-atlas-params.yaml
  tasks/managed/collect-atlas-params/tests/test-collect-atlas-params-prod.yaml
  tasks/managed/collect-atlas-params/tests/test-collect-atlas-params-stage.yaml
  tasks/managed/upload-sbom-to-atlas/README.md
  tasks/managed/upload-sbom-to-atlas/tests/pre-apply-task-hook.sh
  tasks/managed/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-curl-fail.yaml
  tasks/managed/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-cyclonedx.yaml
  tasks/managed/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-spdx.yaml
  tasks/managed/upload-sbom-to-atlas/upload-sbom-to-atlas.yaml
Labels: lgtm, ok-to-test

#887 fix(RELEASE-1508): update-fbc-catalog safe checks
  tasks/internal/update-fbc-catalog-task/README.md
  tasks/internal/update-fbc-catalog-task/tests/mocks.sh
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-error.yaml
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-hotfix.yaml
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-prod.yaml
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-retry-complete.yaml
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-retry-in-progress.yaml
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-retry-outdated.yaml
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-staged-index.yaml
  tasks/internal/update-fbc-catalog-task/update-fbc-catalog-task.yaml
Labels: ok-to-test

#913 fix: increase set-advisory-severity IR timeout
  tasks/managed/set-advisory-severity/README.md
  tasks/managed/set-advisory-severity/set-advisory-severity.yaml
Labels: lgtm

#875 feat: Add the push rpm to koji pipeline and tasks
  pipelines/managed/push-rpm-to-koji/README.md
  pipelines/managed/push-rpm-to-koji/push-rpm-to-koji.yaml
  schema/dataKeys.json
  tasks/managed/collect-push-rpm-params/README.md
  tasks/managed/collect-push-rpm-params/collect-push-rpm-params.yaml
  tasks/managed/collect-push-rpm-params/tests/test-collect-push-rpm-params.yaml
  tasks/managed/push-rpm-to-koji/README.md
  tasks/managed/push-rpm-to-koji/push-rpm-to-koji.yaml
  tasks/managed/push-rpm-to-koji/tests/mocks.sh
  tasks/managed/push-rpm-to-koji/tests/pre-apply-task-hook.sh
  tasks/managed/push-rpm-to-koji/tests/test-push-rpm-to-koji.yaml
Labels: lgtm, ok-to-test

#916 refactor: update existing internal-services manager prs
  tasks/tenant/update-manager-image-in-git/README.md
  tasks/tenant/update-manager-image-in-git/tests/mocks.sh
  tasks/tenant/update-manager-image-in-git/tests/test-update-manager-fail-create-pr.yaml
  tasks/tenant/update-manager-image-in-git/update-manager-image-in-git.yaml
Labels: lgtm

#919 fix: temporarily allow upload-product-sbom to fail
  pipelines/managed/rh-advisories/README.md
  pipelines/managed/rh-advisories/rh-advisories.yaml
Labels: lgtm

#923 fix: allow close-advisory-issues to fail
  pipelines/managed/rh-advisories/README.md
  pipelines/managed/rh-advisories/rh-advisories.yaml
Labels: lgtm
