Repository konflux-ci/release-service-catalog, pull requests merged in 2025-07, with the labels that each got.

#1162 fix: add retries to github merges
  integration-tests/lib/test-functions.sh
Labels: lgtm

#1165 chore(RELEASE-1142): react to merge_group events
  .github/workflows/lint.yaml
  .github/workflows/tekton_task_tests.yaml
Labels: lgtm

#1186 fix: add pull secret for fbc preview index image
  integration-tests/fbc-release/resources/managed/sa.yaml
  integration-tests/fbc-release/vault/managed-secrets.yaml
Labels: lgtm

#1188 chore: remove old secret for registy redhat io
  integration-tests/fbc-release/resources/managed/sa.yaml
  integration-tests/fbc-release/vault/managed-secrets.yaml
Labels: lgtm

#1079 fix(KFLUXSPRT-3673): set timeouts for internal-request
  tasks/managed/add-fbc-contribution/add-fbc-contribution.yaml
  tasks/managed/add-fbc-contribution/tests/mocks.sh
Labels: lgtm, ok-to-test

#1172 feat: use utils image with concurrency limit
  tasks/managed/update-component-sbom/tests/test-update-component-sbom-basic.yaml
  tasks/managed/update-component-sbom/update-component-sbom.yaml
Labels: ok-to-test

#981 feat(CLOUDDST-26262): create pyxis image for operator index images
  pipelines/managed/fbc-release/fbc-release.yaml
  tasks/managed/collect-index-images/README.md
  tasks/managed/collect-index-images/collect-index-images.yaml
  tasks/managed/collect-index-images/tests/test-collect-index-images-hotfix.yaml
  tasks/managed/collect-index-images/tests/test-collect-index-images-multiple-versions.yaml
  tasks/managed/collect-index-images/tests/test-collect-index-images-single-version.yaml
Labels: ok-to-test

#1198 fix: use the right auth on oras manifest of push-rpm-to-koji
  pipelines/managed/push-rpm-to-koji/push-rpm-to-koji.yaml
  tasks/managed/push-rpm-to-koji/push-rpm-to-koji.yaml
Labels: lgtm, ok-to-test

#1155 feat(RELEASE-1691): add new integration pipelines
  integration-tests/pipelines/e2e-tests-kind-pipeline.yaml
  integration-tests/pipelines/e2e-tests-stage-pipeline.yaml
Labels: lgtm

#1156 fix: another arg list too long in filter task
  tasks/managed/filter-already-released-advisory-images/filter-already-released-advisory-images.yaml
Labels: lgtm

#1216 fix: the git url of check-if-related-test
  integration-tests/pipelines/e2e-tests-stage-pipeline.yaml
Labels: lgtm

#1231 fix: increase fbc timeouts in all rpa to 5 hours
  integration-tests/fbc-release/resources/managed/rpa.yaml
Labels: lgtm

#1218 fix(KONFLUX-8821): Increase performance for large snapshots
  tasks/internal/request-and-upload-signature/request-and-upload-signature.yaml
  tasks/internal/request-and-upload-signature/tests/test-request-and-upload-signature-2-references.yaml
  tasks/internal/request-and-upload-signature/tests/test-request-and-upload-signature.yaml
  tasks/managed/create-product-sbom/create-product-sbom.yaml
  tasks/managed/push-snapshot/README.md
  tasks/managed/push-snapshot/push-snapshot.yaml
  tasks/managed/rh-sign-image-cosign/README.md
  tasks/managed/rh-sign-image-cosign/rh-sign-image-cosign.yaml
  tasks/managed/rh-sign-image/README.md
  tasks/managed/rh-sign-image/rh-sign-image.yaml
Labels: lgtm

#1238 feat(ISV-6146): push regeneration data to S3
  pipelines/managed/rh-advisories/rh-advisories.yaml
  tasks/managed/create-product-sbom/README.md
  tasks/managed/create-product-sbom/create-product-sbom.yaml
  tasks/managed/create-product-sbom/tests/mocks.sh
  tasks/managed/create-product-sbom/tests/test-create-product-sbom-basic.yaml
  tasks/managed/update-component-sbom/README.md
  tasks/managed/update-component-sbom/tests/mocks.sh
  tasks/managed/update-component-sbom/tests/test-update-component-sbom-basic.yaml
  tasks/managed/update-component-sbom/update-component-sbom.yaml
  tasks/managed/upload-sbom-to-atlas/README.md
  tasks/managed/upload-sbom-to-atlas/upload-sbom-to-atlas.yaml
Labels: lgtm, ok-to-test

#1245 feat(RELEASE-1765): add collect-task-params managed task
  tasks/managed/collect-task-params/README.md
  tasks/managed/collect-task-params/collect-task-params.yaml
  tasks/managed/collect-task-params/tests/test-collect-task-params-fail-empty-keys.yaml
  tasks/managed/collect-task-params/tests/test-collect-task-params-fail-invalid-index.yaml
  tasks/managed/collect-task-params/tests/test-collect-task-params-fail-missing-resultindex.yaml
  tasks/managed/collect-task-params/tests/test-collect-task-params-fail-no-data.yaml
  tasks/managed/collect-task-params/tests/test-collect-task-params-fail-no-default.yaml
  tasks/managed/collect-task-params/tests/test-collect-task-params-fail-non-integer-index.yaml
  tasks/managed/collect-task-params/tests/test-collect-task-params-fail-not-array.yaml
  tasks/managed/collect-task-params/tests/test-collect-task-params-fail-not-json.yaml
  tasks/managed/collect-task-params/tests/test-collect-task-params.yaml
Labels: lgtm

#1254 fix: krw test for release-to-github
  integration-tests/release-to-github/test.env
  integration-tests/release-to-github/vault/managed-secrets.yaml
Labels: lgtm

#1255 chore: add notes about gh token rotation
  integration-tests/MAINTENANCE.md
Labels: lgtm

#1259 Revert "fix: validate pac repositories (#1257)"
  integration-tests/lib/test-functions.sh
  integration-tests/run-test.sh
  integration-tests/scripts/validate-pac-repository.sh
Labels: lgtm

#1265 chore: runasuser check only if files have changed
  .github/workflows/lint.yaml
Labels: lgtm

#1266 chore: test libs, scripts or runner should trigger
  integration-tests/scripts/find_release_pipelines_from_pr.sh
Labels: lgtm

#1264 fix(KFLUXSPRT-4426): fix argument too long for tasks get-advisory-severity and set-advisory-severity
  pipelines/internal/get-advisory-severity/README.md
  pipelines/internal/get-advisory-severity/get-advisory-severity.yaml
  tasks/internal/get-advisory-severity/README.md
  tasks/internal/get-advisory-severity/get-advisory-severity.yaml
  tasks/internal/get-advisory-severity/tests/test-get-advisory-severity-component.yaml
  tasks/internal/get-advisory-severity/tests/test-get-advisory-severity-empty-component-impact.yaml
  tasks/internal/get-advisory-severity/tests/test-get-advisory-severity-no-cves.yaml
  tasks/internal/get-advisory-severity/tests/test-get-advisory-severity.yaml
  tasks/managed/set-advisory-severity/set-advisory-severity.yaml
Labels: lgtm

#1277 fix: add missing params to push-oot-kmods (#1272)
  pipelines/managed/push-oot-kmods/push-oot-kmods.yaml
Labels: lgtm
