Repository konflux-ci/release-service-catalog, pull requests merged in 2025-05, with the labels that each got.

#932 fix: gitlint regular expression string
  .github/gitlint/contrib_format_conventional_commits.py
Labels: needs-ok-to-test

#915 feat(RELEASE-1341): fbc ir should use release sa
  schema/dataKeys.json
  tasks/managed/add-fbc-contribution/README.md
  tasks/managed/add-fbc-contribution/add-fbc-contribution.yaml
  tasks/managed/add-fbc-contribution/tests/test-add-fbc-contribution-hotfix.yaml
  tasks/managed/add-fbc-contribution/tests/test-add-fbc-contribution-pre-ga.yaml
  tasks/managed/add-fbc-contribution/tests/test-add-fbc-contribution.yaml
Labels: ok-to-test

#936 feat(RELEASE-1536): check for advisory id before creating it
  tasks/internal/create-advisory-task/README.md
  tasks/internal/create-advisory-task/create-advisory-task.yaml
  tasks/internal/create-advisory-task/tests/mocks.sh
  tasks/internal/create-advisory-task/tests/test-create-advisory-fail-existing-id.yaml
Labels: lgtm

#943 fix: use correct param name in blob-signing pipeline
  pipelines/internal/blob-signing-pipeline/README.md
  pipelines/internal/blob-signing-pipeline/blob-signing-pipeline.yaml
Labels: lgtm

#944 fix: ensure severity is present in advisory
  pipelines/managed/rh-advisories/README.md
  pipelines/managed/rh-advisories/rh-advisories.yaml
Labels: lgtm

#920 feat(ISV-5887): force retry of S3 PUT request
  pipelines/managed/rh-advisories/README.md
  pipelines/managed/rh-advisories/rh-advisories.yaml
  tasks/managed/upload-sbom-to-atlas/README.md
  tasks/managed/upload-sbom-to-atlas/upload-sbom-to-atlas.yaml
Labels: lgtm, ok-to-test

#956 docs: improve error message for unlisted cve in embargo-check
  tasks/managed/embargo-check/README.md
  tasks/managed/embargo-check/embargo-check.yaml
Labels: lgtm

#953 chore(KFLUXVNGD-311): update appstudio-utils image ref
  tasks/managed/update-trusted-tasks/README.md
  tasks/managed/update-trusted-tasks/update-trusted-tasks.yaml
Labels: lgtm, ok-to-test

#942 fix: processing of long argument list with jq
  tasks/internal/create-advisory-task/README.md
  tasks/internal/create-advisory-task/create-advisory-task.yaml
Labels: lgtm

#958 fix: re-add public field for issues
  tasks/internal/create-advisory-task/README.md
  tasks/internal/create-advisory-task/create-advisory-task.yaml
  tasks/internal/create-advisory-task/tests/test-create-advisory-fail.yaml
  tasks/internal/create-advisory-task/tests/test-create-advisory-idempotency-multiple-image.yaml
  tasks/internal/create-advisory-task/tests/test-create-advisory-idempotency-single-image.yaml
  tasks/internal/create-advisory-task/tests/test-create-advisory.yaml
Labels: lgtm

#940 feat(CLDX-378): skip setting advisory severity for generic artifacts
  tasks/managed/set-advisory-severity/README.md
  tasks/managed/set-advisory-severity/set-advisory-severity.yaml
  tasks/managed/set-advisory-severity/tests/test-set-advisory-severity-generic-artifact.yaml
Labels: ok-to-test

#941 feat(CLDX-380): enable embargo check for generic artifacts
  tasks/managed/embargo-check/README.md
  tasks/managed/embargo-check/embargo-check.yaml
  tasks/managed/embargo-check/tests/test-embargo-check-embargoed-cve-artifact.yaml
  tasks/managed/embargo-check/tests/test-embargo-check-rh-issue-artifact.yaml
Labels: lgtm, ok-to-test

#964 feat(CLDX-379): use signing key from configMap
  pipelines/internal/push-artifacts-to-cdn/README.md
  pipelines/internal/push-artifacts-to-cdn/push-artifacts-to-cdn.yaml
  tasks/internal/push-artifacts-to-cdn-task/README.md
  tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-gzip.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-no-cgwfileprefix.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-no-cgwproductcode.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-no-cgwproductname.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-no-cgwproductversionname.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-no-containerimage.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-no-stageddestination.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-no-stagedfilesfilename.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-no-stagedfilessource.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-no-stagedversion.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-oras-pull.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-pulp-push.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-fail-same-filename.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-multiple-components.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-only-cdn.yaml
  tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn.yaml
  tasks/managed/push-artifacts-to-cdn/README.md
  tasks/managed/push-artifacts-to-cdn/push-artifacts-to-cdn.yaml
  tasks/managed/push-artifacts-to-cdn/tests/pre-apply-task-hook.sh
  tasks/managed/push-artifacts-to-cdn/tests/test-push-artifacts-to-cdn-fail-ir-failure.yaml
  tasks/managed/push-artifacts-to-cdn/tests/test-push-artifacts-to-cdn-fail-no-contentgateway-data.yaml
  tasks/managed/push-artifacts-to-cdn/tests/test-push-artifacts-to-cdn-fail-no-release-author.yaml
  tasks/managed/push-artifacts-to-cdn/tests/test-push-artifacts-to-cdn-fail-no-snapshot.yaml
  tasks/managed/push-artifacts-to-cdn/tests/test-push-artifacts-to-cdn-fail-plr-failure.yaml
  tasks/managed/push-artifacts-to-cdn/tests/test-push-artifacts-to-cdn-production.yaml
  tasks/managed/push-artifacts-to-cdn/tests/test-push-artifacts-to-cdn-qa.yaml
  tasks/managed/push-artifacts-to-cdn/tests/test-push-artifacts-to-cdn-results-plr.yaml
  tasks/managed/push-artifacts-to-cdn/tests/test-push-artifacts-to-cdn-results.yaml
  tasks/managed/push-artifacts-to-cdn/tests/test-push-artifacts-to-cdn-stage.yaml
Labels: lgtm, ok-to-test

#918 feat(RHELWF-12643): add support for importing draft builds
  pipelines/managed/push-rpm-to-koji/push-rpm-to-koji.yaml
  schema/dataKeys.json
  tasks/managed/collect-push-rpm-params/tests/test-collect-push-rpm-params.yaml
  tasks/managed/push-rpm-to-koji/README.md
  tasks/managed/push-rpm-to-koji/push-rpm-to-koji.yaml
  tasks/managed/push-rpm-to-koji/tests/test-push-rpm-to-koji.yaml
Labels: ok-to-test

#965 feat(CLDX-382): Add populate-release-notes-binaries step
  tasks/managed/populate-release-notes/README.md
  tasks/managed/populate-release-notes/populate-release-notes.yaml
  tasks/managed/populate-release-notes/tests/test-populate-release-notes-cves-artifacts.yaml
Labels: lgtm, ok-to-test

#970 revert(RELEASE-1636): undo changes from PR 951
  tasks/managed/create-advisory/README.md
  tasks/managed/create-advisory/create-advisory.yaml
  tasks/managed/create-advisory/tests/mocks.sh
  tasks/managed/embargo-check/README.md
  tasks/managed/embargo-check/embargo-check.yaml
  tasks/managed/embargo-check/tests/mocks.sh
  tasks/managed/push-disk-images/README.md
  tasks/managed/push-disk-images/push-disk-images.yaml
  tasks/managed/push-disk-images/tests/mocks.sh
  tasks/managed/set-advisory-severity/README.md
  tasks/managed/set-advisory-severity/set-advisory-severity.yaml
  tasks/managed/set-advisory-severity/tests/mocks.sh
  tasks/managed/sign-base64-blob/README.md
  tasks/managed/sign-base64-blob/sign-base64-blob.yaml
Labels: lgtm

#974 Revert "refactor(RELEASE-1560): update to remove .contentGateway"
  tasks/managed/extract-binaries-from-image/README.md
  tasks/managed/extract-binaries-from-image/extract-binaries-from-image.yaml
  tasks/managed/extract-binaries-from-image/tests/test-extract-binaries-multiple-components-desired-only.yaml
  tasks/managed/publish-to-cgw/README.md
  tasks/managed/publish-to-cgw/publish-to-cgw.yaml
  tasks/managed/publish-to-cgw/tests/test-publish-to-cgw-create-all.yaml
  tasks/managed/publish-to-cgw/tests/test-publish-to-cgw-create-and-skip.yaml
  tasks/managed/publish-to-cgw/tests/test-publish-to-cgw-skip-all.yaml
Labels: lgtm

#982 fix(RELEASE-1645): remove skip-checks
  .tekton/release-service-catalog-pull-request.yaml
  .tekton/release-service-catalog-push.yaml
Labels: lgtm

#979 fix(RELEASE-1645): collector ci fixes
  .tekton/release-service-catalog-pull-request.yaml
  Dockerfile
  integration-tests/collectors/utils/cleanup-resources.sh
  integration-tests/lib/test-functions.sh
  integration-tests/scripts/get-advisory-content.sh
  integration-tests/scripts/wait-for-release.sh
  integration-tests/setup/README.md
  integration-tests/setup/resources/tenant/service_account_token.yaml
  integration-tests/setup/scripts/get-kubeconfig-from-service-account.sh
  pipelines/internal/request-advisory-oci-artifact/README.md
  pipelines/internal/request-advisory-oci-artifact/request-advisory-oci-artifact.yaml
Labels: lgtm

#986 feat(ROK-446): avoid Koji import if contract verification fails
  pipelines/managed/push-rpm-to-koji/README.md
  pipelines/managed/push-rpm-to-koji/push-rpm-to-koji.yaml
Labels: lgtm, ok-to-test
