Repository konflux-ci/release-service-catalog, pull requests merged in 2025-02, with the labels that each got.

#786 feat(ISV-5571): ignore SBOM-related task errors in rh-advisories
  tasks/managed/upload-sbom-to-atlas/README.md
  tasks/managed/upload-sbom-to-atlas/tests/mocks.sh
  tasks/managed/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-curl-fail.yaml
  tasks/managed/upload-sbom-to-atlas/upload-sbom-to-atlas.yaml
Labels: lgtm, ok-to-test

#810 fix(KONFLUX-6715): make sure indexImageDigests result is one line only
  tasks/internal/update-fbc-catalog-task/README.md
  tasks/internal/update-fbc-catalog-task/tests/mocks.sh
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-hotfix.yaml
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-prod.yaml
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-retry-complete.yaml
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-retry-in-progress.yaml
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-retry-outdated.yaml
  tasks/internal/update-fbc-catalog-task/tests/test-update-fbc-catalog-staged-index.yaml
  tasks/internal/update-fbc-catalog-task/update-fbc-catalog-task.yaml
Labels: lgtm

#792 feat: use 4h timeout default rh-advisories and rh-push-to-registry-redhat-io pipelines
  pipelines/managed/rh-advisories/rh-advisories.yaml
  pipelines/managed/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
Labels: ok-to-test

#821 fix(RELEASE-1405): remove advisory severity for non RHSA
  tasks/managed/set-advisory-severity/README.md
  tasks/managed/set-advisory-severity/set-advisory-severity.yaml
  tasks/managed/set-advisory-severity/tests/test-set-advisory-severity-not-rhsa-user-severity.yaml
Labels: lgtm

#805 feat(RELEASE-1252): make run-file-updates task idempotent
  tasks/internal/process-file-updates-task/README.md
  tasks/internal/process-file-updates-task/process-file-updates-task.yaml
  tasks/internal/process-file-updates-task/tests/mocks.sh
  tasks/internal/process-file-updates-task/tests/test-process-file-updates-replacements-idempotent.yaml
  tasks/managed/run-file-updates/run-file-updates.yaml
Labels: lgtm

#828 fix: get-advisory-severity jq issue
  tasks/internal/get-advisory-severity/README.md
  tasks/internal/get-advisory-severity/get-advisory-severity.yaml
  tasks/internal/get-advisory-severity/tests/test-get-advisory-severity.yaml
Labels: lgtm

#830 feat(RELEASE-1451): add invalid key test for `releaseNotes.issues`
  tasks/managed/check-data-keys/tests/test-check-data-keys-invalid-issues-in-releasenotes-key.yaml
Labels: lgtm

#831 fix(RELEASE-1433): reapply changes in create-pyxis-image
  tasks/managed/create-pyxis-image/README.md
  tasks/managed/create-pyxis-image/create-pyxis-image.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-dockerfile-not-found.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-fail-dockerfile-not-pulled.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-multi-arch.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-multi-containerimages-one-arch.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-oci-artifact.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-multi-arch.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-rhpush-and-commontag.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-skip-layers.yaml
  tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-with-gzipped-layers.yaml
Labels: lgtm
