Repository konflux-ci/release-service-catalog, pull requests merged in 2025-06, with the labels that each got.

#992 fix: improve collector pipeline error display
  integration-tests/scripts/wait-for-release.sh
Labels: lgtm

#1005 fix: increase mem for verify-access-to-resources
  tasks/managed/verify-access-to-resources/README.md
  tasks/managed/verify-access-to-resources/verify-access-to-resources.yaml
Labels: lgtm

#1007 fix: improve wait-for-release.sh
  integration-tests/scripts/wait-for-release.sh
Labels: lgtm

#999 fix(ISV-5990): fix SBOM update silent failures
  tasks/managed/update-component-sbom/README.md
  tasks/managed/update-component-sbom/tests/test-update-component-sbom-basic.yaml
  tasks/managed/update-component-sbom/update-component-sbom.yaml
Labels: ok-to-test

#993 feat(RELEASE-567): add compute resource limits to tasks
  tasks/managed/add-fbc-contribution/README.md
  tasks/managed/add-fbc-contribution/add-fbc-contribution.yaml
  tasks/managed/apply-mapping/README.md
  tasks/managed/apply-mapping/apply-mapping.yaml
  tasks/managed/check-data-keys/README.md
  tasks/managed/check-data-keys/check-data-keys.yaml
  tasks/managed/cleanup-internal-requests/README.md
  tasks/managed/cleanup-internal-requests/cleanup-internal-requests.yaml
  tasks/managed/close-advisory-issues/README.md
  tasks/managed/close-advisory-issues/close-advisory-issues.yaml
Labels: ok-to-test

#1015 feat: remove SBOM conversion
  tasks/managed/upload-sbom-to-atlas/README.md
  tasks/managed/upload-sbom-to-atlas/tests/mocks.sh
  tasks/managed/upload-sbom-to-atlas/tests/pre-apply-task-hook.sh
  tasks/managed/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-curl-fail.yaml
  tasks/managed/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-cyclonedx.yaml
  tasks/managed/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas.yaml
  tasks/managed/upload-sbom-to-atlas/upload-sbom-to-atlas.yaml
Labels: ok-to-test

#1023 feat(RELEASE-1561): remove push-binaries-to-dev-portal pipeline
  pipelines/managed/push-binaries-to-dev-portal/README.md
  pipelines/managed/push-binaries-to-dev-portal/push-binaries-to-dev-portal.yaml
  tasks/managed/prepare-exodus-params/README.md
  tasks/managed/prepare-exodus-params/prepare-exodus-params.yaml
  tasks/managed/prepare-exodus-params/tests/test-prepare-exodus-params-cdn-live.yaml
  tasks/managed/prepare-exodus-params/tests/test-prepare-exodus-params-cdn-qa.yaml
  tasks/managed/prepare-exodus-params/tests/test-prepare-exodus-params-cdn-stage.yaml
  tasks/managed/publish-to-cgw/README.md
  tasks/managed/publish-to-cgw/publish-to-cgw.yaml
  tasks/managed/publish-to-cgw/tests/mocks.sh
  tasks/managed/publish-to-cgw/tests/pre-apply-task-hook.sh
  tasks/managed/publish-to-cgw/tests/test-publish-to-cgw-create-all.yaml
  tasks/managed/publish-to-cgw/tests/test-publish-to-cgw-create-and-skip.yaml
  tasks/managed/publish-to-cgw/tests/test-publish-to-cgw-skip-all.yaml
  tasks/managed/push-to-cdn/README.md
  tasks/managed/push-to-cdn/push-to-cdn.yaml
  tasks/managed/push-to-cdn/tests/mocks.sh
  tasks/managed/push-to-cdn/tests/pre-apply-task-hook.sh
  tasks/managed/push-to-cdn/tests/test-push-to-cdn.yaml
  tasks/managed/sign-binaries/README.md
  tasks/managed/sign-binaries/sign-binaries.yaml
  tasks/managed/sign-binaries/tests/checksum_mocks.sh
  tasks/managed/sign-binaries/tests/mac_mocks.sh
  tasks/managed/sign-binaries/tests/mocks.sh
  tasks/managed/sign-binaries/tests/pre-apply-task-hook.sh
  tasks/managed/sign-binaries/tests/test-sign-binaries-checksum.yaml
  tasks/managed/sign-binaries/tests/test-sign-binaries.yaml
Labels: lgtm

#1004 feat(RELEASE-567): add compute resource limits to tasks
  tasks/managed/check-fbc-packages/README.md
  tasks/managed/check-fbc-packages/check-fbc-packages.yaml
  tasks/managed/cleanup-workspace/README.md
  tasks/managed/cleanup-workspace/cleanup-workspace.yaml
  tasks/managed/collect-data/README.md
  tasks/managed/collect-data/collect-data.yaml
  tasks/managed/push-rpm-data-to-pyxis/README.md
  tasks/managed/push-rpm-data-to-pyxis/push-rpm-data-to-pyxis.yaml
  tasks/managed/sign-index-image/README.md
  tasks/managed/sign-index-image/sign-index-image.yaml
Labels: lgtm

#1039 fix: increase memory on update-fbc-catalog task
  tasks/internal/update-fbc-catalog-task/update-fbc-catalog-task.yaml
Labels: lgtm

#1051 feat(RELEASE-1612): enable trusted artifacts in base64-encode-checksum task
  pipelines/managed/release-to-github/README.md
  pipelines/managed/release-to-github/release-to-github.yaml
  tasks/managed/base64-encode-checksum/README.md
  tasks/managed/base64-encode-checksum/base64-encode-checksum.yaml
  tasks/managed/base64-encode-checksum/tests/run.yaml
  tasks/managed/base64-encode-checksum/tests/test-base64-encode-checksum.yaml
Labels: lgtm

#1062 feat(ISV-6033): limit SBOM update concurrency
  tasks/managed/update-component-sbom/README.md
  tasks/managed/update-component-sbom/tests/test-update-component-sbom-basic.yaml
  tasks/managed/update-component-sbom/update-component-sbom.yaml
Labels: lgtm, ok-to-test

#1061 chore: support collectors and integration-tests when finding pipelines
  integration-tests/scripts/find_release_pipelines_from_pr.sh
Labels: lgtm

#1037 feat(RELEASE-567): add compute resource limits to tasks
  tasks/internal/create-advisory-oci-artifact-task/README.md
  tasks/internal/create-advisory-oci-artifact-task/create-advisory-oci-artifact-task.yaml
  tasks/internal/filter-already-released-advisory-images-task/README.md
  tasks/internal/filter-already-released-advisory-images-task/filter-already-released-advisory-images-task.yaml
  tasks/internal/pulp-push-disk-images/README.md
  tasks/internal/pulp-push-disk-images/pulp-push-disk-images.yaml
  tasks/internal/push-artifacts-to-cdn-task/README.md
  tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
  tasks/internal/request-advisory-oci-artifact/README.md
  tasks/internal/request-advisory-oci-artifact/request-advisory-oci-artifact.yaml
  tasks/internal/update-fbc-catalog-task/update-fbc-catalog-task.yaml
Labels: lgtm

#1029 feat(CLDX-268): add advisory tasks to push-artifacts-to-cdn pipeline
  pipelines/managed/push-artifacts-to-cdn/README.md
  pipelines/managed/push-artifacts-to-cdn/push-artifacts-to-cdn.yaml
  schema/dataKeys.json
Labels: ok-to-test

#1070 fix: resources for request-advisory-oci-artifact
  tasks/internal/request-advisory-oci-artifact/README.md
  tasks/internal/request-advisory-oci-artifact/request-advisory-oci-artifact.yaml
Labels: lgtm

#1071 chore: improve status of skipped tests
  integration-tests/pipelines/e2e-tests-staging-pipeline.yaml
Labels: lgtm

#1081 fix: fix ta references for push-artifacts-to-cdn
  pipelines/managed/push-artifacts-to-cdn/README.md
  pipelines/managed/push-artifacts-to-cdn/push-artifacts-to-cdn.yaml
Labels: lgtm

#1084 feat(RELEASE-567): add docs and checks for computeResources
  .github/scripts/tkn_check_compute_resources.sh
  .github/workflows/lint.yaml
  CONTRIBUTING.md
Labels: lgtm

#1089 fix: adjust rh-sign-image computeResources
  tasks/managed/rh-sign-image/README.md
  tasks/managed/rh-sign-image/rh-sign-image.yaml
Labels: lgtm

#1091 feat(RELEASE-1618): convert collect-slack-notification-params to use trusted artifacts
  pipelines/managed/rhtap-service-push/README.md
  pipelines/managed/rhtap-service-push/rhtap-service-push.yaml
  tasks/managed/collect-slack-notification-params/README.md
  tasks/managed/collect-slack-notification-params/collect-slack-notification-params.yaml
  tasks/managed/collect-slack-notification-params/tests/test-collect-slack-notification-params-no-secret-in-data.yaml
  tasks/managed/collect-slack-notification-params/tests/test-collect-slack-notification-params.yaml
Labels: lgtm

#1092 feat(RELEASE-1698): convert send-slack-notification to use trusted artifacts
  pipelines/managed/rhtap-service-push/README.md
  pipelines/managed/rhtap-service-push/rhtap-service-push.yaml
  tasks/managed/send-slack-notification/README.md
  tasks/managed/send-slack-notification/send-slack-notification.yaml
  tasks/managed/send-slack-notification/tests/mocks.sh
  tasks/managed/send-slack-notification/tests/pre-apply-task-hook.sh
  tasks/managed/send-slack-notification/tests/test-send-slack-notification-no-secret.yaml
  tasks/managed/send-slack-notification/tests/test-send-slack-notification.yaml
Labels: lgtm

#1098 fix(KFLUXSPRT-3846): critical typo in sign-index-image
  tasks/managed/add-fbc-contribution/add-fbc-contribution.yaml
  tasks/managed/sign-index-image/README.md
  tasks/managed/sign-index-image/sign-index-image.yaml
  tasks/managed/sign-index-image/tests/test-sign-index-image-multicomponent.yaml
  tasks/managed/sign-index-image/tests/test-sign-index-image-plr.yaml
  tasks/managed/sign-index-image/tests/test-sign-index-image-with-pullspec-rewrite.yaml
  tasks/managed/sign-index-image/tests/test-sign-index-image.yaml
Labels: lgtm

#1043 feat(RELEASE-1584): fbc-release e2e test
  .yamllint
  integration-tests/fbc-release/README.md
  integration-tests/fbc-release/resources/managed/ec-policy.yaml
  integration-tests/fbc-release/resources/managed/kustomization.yaml
  integration-tests/fbc-release/resources/managed/rpa.yaml
  integration-tests/fbc-release/resources/managed/sa-rolebinding.yaml
  integration-tests/fbc-release/resources/managed/sa.yaml
  integration-tests/fbc-release/resources/tenant/application.yaml
  integration-tests/fbc-release/resources/tenant/component.yaml
  integration-tests/fbc-release/resources/tenant/kustomization.yaml
  integration-tests/fbc-release/resources/tenant/rp.yaml
  integration-tests/fbc-release/resources/tenant/sa-rolebinding.yaml
  integration-tests/fbc-release/resources/tenant/sa.yaml
  integration-tests/fbc-release/test.env
  integration-tests/fbc-release/test.sh
  integration-tests/fbc-release/vault/managed-secrets.yaml
  integration-tests/fbc-release/vault/tenant-secrets.yaml
  integration-tests/lib/test-functions.sh
  integration-tests/run-test.sh
  integration-tests/scripts/delete-old-branches.sh
  integration-tests/scripts/wait-for-release.sh
Labels: lgtm

#1109 feat: support new fields in rpm data
  tasks/managed/push-rpm-data-to-pyxis/push-rpm-data-to-pyxis.yaml
  tasks/managed/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-cyclonedx.yaml
  tasks/managed/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-failure.yaml
  tasks/managed/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-multi-arch.yaml
  tasks/managed/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-parallel.yaml
  tasks/managed/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-retry.yaml
  tasks/managed/push-rpm-data-to-pyxis/tests/test-push-rpm-data-to-pyxis-single-arch.yaml
Labels: lgtm

#1112 fix: pass correct epoch to Koji build
  tasks/managed/push-rpm-to-koji/push-rpm-to-koji.yaml
Labels: ok-to-test

#1141 fix: error handling in request-and-upload-signature
  tasks/internal/request-and-upload-signature/request-and-upload-signature.yaml
  tasks/internal/request-and-upload-signature/tests/test-request-and-upload-signature-2-references.yaml
  tasks/internal/request-and-upload-signature/tests/test-request-and-upload-signature-failed-messages.yaml
Labels: lgtm

#1150 fix: result too long in filter-already-released task
  tasks/internal/filter-already-released-advisory-images-task/filter-already-released-advisory-images-task.yaml
  tasks/internal/filter-already-released-advisory-images-task/tests/test-filter-already-released-advisory-images.yaml
  tasks/internal/filter-already-released-advisory-images-task/tests/test-filter-no-advisory-directory.yaml
  tasks/managed/filter-already-released-advisory-images/filter-already-released-advisory-images.yaml
  tasks/managed/filter-already-released-advisory-images/tests/mocks.sh
Labels: lgtm
